import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <main className="flex flex-row">
        <SideBar />
        {children}
        </main>
      </body>
    </html>
  );
}
